FROM alpine:3.19

ARG PB_VERSION=0.39.3

RUN apk add --no-cache unzip ca-certificates wget

RUN wget -O /tmp/pb.zip "https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_amd64.zip" \
    && unzip -d /pb /tmp/pb.zip pocketbase \
    && rm /tmp/pb.zip \
    && chmod +x /pb/pocketbase

EXPOSE 8090

VOLUME /pb_data

CMD ["/pb/pocketbase", "serve", "--http=0.0.0.0:8090", "--dir=/pb_data"]
