FROM alpine:3.19

ARG PB_VERSION=0.39.3

RUN apk add --no-cache unzip ca-certificates wget

RUN PB_ARCH="amd64" && \
    case $(uname -m) in \
        aarch64) PB_ARCH="arm64" ;; \
        armv7l)  PB_ARCH="armv7" ;; \
    esac && \
    wget -O /tmp/pb.zip "https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_${PB_ARCH}.zip" \
    && unzip -d /pb /tmp/pb.zip pocketbase \
    && rm /tmp/pb.zip \
    && chmod +x /pb/pocketbase

EXPOSE 8090

VOLUME /pb_data

CMD ["/pb/pocketbase", "serve", "--http=0.0.0.0:8090", "--dir=/pb_data"]
